name: "Lesson 3, Exercise 1: The Caller Workflow"

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      actor: ${{ github.actor }}

    #secrets:
    #  my_secret: ${{ secrets.MY_SECRET }}
