
# .github/workflows/caller-workflow.yml - ChatGPT generated, updated
name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/called-workflow.yaml
# When you want to use an input's default value, and there is only one input, comment the "with:" directive    
#    with: 
      # No input provided for 'name', so the default 'User' will be used
#    with:
#      name: ${{ github.actor }}
