name: "Lesson 3 - Exercise 1 - Reusable Workflow"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
        actor:
            description: "The actor of the workflow!"
            required: true
            # TODO: The default value is not working. Investigate
            default: "Me, me, me, me!"
            type: string

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: A message
        run: |
          echo "The reusable workflow was called by: >>> $ACTOR <<<"
        env:
          ACTOR: ${{ inputs.actor }}
