name: "Lesson 3 - Exercise 1 - Reusable Workflow"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      actor:
        description: "The actor of the workflow!"
        # If you want to use a default value for any input, use required: false
        required: false
        default: "Me, me, me, me!"
        type: string
      repo:
        description: "The repo from where this workflow was called"
        required: true
        type: string

          
jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: A message
        run: |
          echo "The reusable workflow was called by: >>> $ACTOR <<< using job: >>> ${{ inputs.repo }} <<<"
        env:
          ACTOR: ${{ inputs.actor }}
          #REPO: ${{ inputs.repo }}
