honame: "Lesson 3 - Exercise 1 - Reusable Workflow"

on:
  workflow_call:
    inputs:
        actor:
            description: "The actor of the workflow!"
            required: true
            default: "Me, me, me, me!"

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: A message
        run: |
          echo "The reusable workflow was called by: >>> $ACTOR <<<"
        env:
          ACTOR: ${{ inputs.actor }}
